[platformio]
default_envs = pcb2_stm32

[env:pcb2_stm32]
platform = ststm32
board = black_f407zg
framework = stm32cube
upload_protocol = stlink
debug_tool = stlink
build_flags =
    -D HSE_VALUE=25000000UL
    -D PCB_SERVO_ID=3
    -D CALIBRATE_ZERO_ON_BOOT=0
    -D CALIBRATE_SET_ORIGIN_ON_BOOT=0
    -D SCAN_SERVO_IDS_ON_BOOT=0
    -D READ_SERVO_ANGLE_ON_BOOT=0
    -D SERVO_STARTUP_TEST=0
monitor_speed = 921600
