#pragma once

#include "driver/gpio.h"

/* 2026-07-31 robot-controller schematic, ESP32-S3-WROOM-1-N16R8. */
#define PCB_TEST_PIN_DRV_NSLEEP GPIO_NUM_3
#define PCB_TEST_PIN_DRV_NFAULT GPIO_NUM_4
#define PCB_TEST_PIN_DRV_AIN1   GPIO_NUM_46
#define PCB_TEST_PIN_DRV_AIN2   GPIO_NUM_9
#define PCB_TEST_PIN_DRV_BIN1   GPIO_NUM_5
#define PCB_TEST_PIN_DRV_BIN2   GPIO_NUM_6
#define PCB_TEST_PIN_SERVO_PWM  GPIO_NUM_45
#define PCB_TEST_PIN_MAGNET     GPIO_NUM_35

#define PCB_TEST_UART_BAUD_RATE       115200
#define PCB_TEST_MOTOR_PWM_HZ         16000
#define PCB_TEST_SERVO_PWM_HZ         50
#define PCB_TEST_SERVO_MIN_PULSE_US   500
#define PCB_TEST_SERVO_MAX_PULSE_US   2500
#define PCB_TEST_OUTPUT_TIMEOUT_MS    5000
#define PCB_TEST_AUTO_MOTOR_PERCENT   10

