[platformio]
default_envs = pcb1

[env]
platform = espressif32
board = esp32dev
framework = arduino
upload_speed = 921600
monitor_speed = 921600
lib_deps =
    https://github.com/Links2004/arduinoWebSockets.git
build_flags =
    -D CORE_DEBUG_LEVEL=5
    -D CONFIG_ARDUHAL_LOG_COLORS=1

[env:pcb1]
build_flags =
    ${env.build_flags}
    -D ROBOT_BOARD_INDEX=1

[env:pcb2]
build_flags =
    ${env.build_flags}
    -D ROBOT_BOARD_INDEX=2

[env:pcb3]
build_flags =
    ${env.build_flags}
    -D ROBOT_BOARD_INDEX=3
